name: '🐛 Bug Report'
description: 'Report an bug'
labels: ['unconfirm']
type: Bug
body:
  - type: dropdown
    attributes:
      label: '📦 Deployment Platform'
      description: 'For Web users: where is LobeChat deployed? (Desktop App users can skip)'
      multiple: true
      options:
        - 'Official Preview'
        - 'Official Cloud'
        - 'Vercel'
        - 'Zeabur'
        - 'Sealos'
        - 'Netlify'
        - 'Self hosting Docker'
        - 'N/A (Desktop/Mobile App)'
        - 'Other'
    validations:
      required: false
  - type: dropdown
    attributes:
      label: '🔧 Deployment Mode'
      description: 'For Docker users only: which image are you using?'
      multiple: true
      options:
        - 'client db (lobe-chat image)'
        - 'client pgelite db (lobe-chat-pglite image)'
        - 'server db (lobe-chat-database image)'
        - 'N/A (Not using Docker)'
    validations:
      required: false
  - type: input
    attributes:
      label: '📌 Version'
    validations:
      required: true

  - type: dropdown
    attributes:
      label: '💻 Operating System'
      multiple: true
      options:
        - 'Windows'
        - 'macOS'
        - 'Ubuntu'
        - 'Other Linux'
        - 'iOS'
        - 'Android'
        - 'Other'
    validations:
      required: true
  - type: dropdown
    attributes:
      label: '📱 Client Type'
      description: 'Select how you are accessing LobeChat'
      multiple: true
      options:
        - 'Web (Desktop Browser)'
        - 'Web (Mobile Browser)'
        - 'Desktop App (Electron)'
        - 'Mobile App (React Native)'
        - 'Other'
    validations:
      required: true
  - type: dropdown
    attributes:
      label: '🌐 Browser'
      multiple: true
      options:
        - 'Chrome'
        - 'Edge'
        - 'Safari'
        - 'Firefox'
        - 'Other'
    validations:
      required: true
  - type: textarea
    attributes:
      label: '🐛 Bug Description'
      description: A clear and concise description of the bug, if the above option is `Other`, please also explain in detail.
    validations:
      required: true
  - type: textarea
    attributes:
      label: '📷 Recurrence Steps'
      description: A clear and concise description of how to recurrence.
  - type: textarea
    attributes:
      label: '🚦 Expected Behavior'
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: '📝 Additional Information'
      description: If your problem needs further explanation, or if the issue you're seeing cannot be reproduced in a gist, please add more information here.
